# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# mkdocs gh-deploy --force
site_name: My site
site_url: https://blog.d111kc.top
theme:
  name: material
  custom_dir: overrides
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font: false
  language: zh
  # logo: assets/logo.png
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt 
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    edit: material/pencil 
    view: material/eye

  # favicon: images/favicon.png

  features:
    - navigation.instant
    - navigation.instant.progress

    - navigation.tracking

    - navigation.tabs
    - navigation.tabs.sticky

    - navigation.sections

    - navigation.prune 

    - navigation.indexes

    - toc.follow

    - navigation.top

    - search.suggest
    - search.highlight
    - search.share

    - header.autohide
    - announce.dismiss

    - navigation.footer

    - content.action.edit
    - content.action.view

extra:
  include: CNAME
  # homepage: https://example.com # click logo and go to homepage
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/d111kc
      name: Follow Me

copyright: Copyright &copy; 2025 d111kc
repo_url: https://github.com/d111kc/blog
repo_name: d111kc/blog
edit_uri: edit/main/docs/

# tweak some colors or change the spacing of certain elements
extra_css:
  - stylesheets/extra.css

# integrate another syntax highlighter or add some custom logic to your theme
extra_javascript:
  - javascripts/extra.js
  - djavascripts/shortcuts.js
  - javascripts/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: On this page
      permalink: ⚓︎
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - git-authors

nav:
  - 主页: index.md
  - 日常:
    - daily/index.md 
    - Page 1: daily/page-1.md
    - Page n: daily/page-n.md
  - 阅读:
    - reading/index.md
  - 日语学习:
    - jp/index.md
    - jp/hiragana.md
  - 英语学习:
    - en/index.md
    - en/cd.md
    - en/fcc.md